name: Production Microservices CI/CD Pipeline

on:
  push:
    branches: [ "feature/jfrog-pipeline" ]

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # SonarQube కి ఫుల్ హిస్టరీ కావాలి కాబట్టి ఇది ముఖ్యం

    # 1. SonarQube Scan Step (Code Quality)
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 2. Build Backend Docker Image
    - name: Build Backend Docker Image
      run: |
        docker build -t localhost:8082/docker-local/backend-service:latest ./backend

    # 3. Build Frontend Docker Image
    - name: Build Frontend Docker Image
      run: |
        docker build -t localhost:8082/docker-local/frontend-service:latest ./frontend

    # 4. Trivy Vulnerability Scan for Docker Images (Security)
    - name: Run Trivy vulnerability scanner (Backend)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'localhost:8082/docker-local/backend-service:latest'
        format: 'table'
        exit-code: '0' # ఇష్యూస్ ఉంటే వార్నింగ్ ఇచ్చి ఆపేయడానికి లేదా '1' ఇస్తే ఫెయిల్ అవడానికి
        severity: 'CRITICAL,HIGH'

    - name: Run Trivy vulnerability scanner (Frontend)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'localhost:8082/docker-local/frontend-service:latest'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'

    # 5. Login to JFrog Artifactory
    - name: Login to JFrog Artifactory
      uses: docker/login-action@v2
      with:
        registry: localhost:8082
        username: admin
        password: password

    # 6. Push Images to Local JFrog Artifactory
    - name: Push Backend Image to JFrog
      run: |
        docker push localhost:8082/docker-local/backend-service:latest

    - name: Push Frontend Image to JFrog
      run: |
        docker push localhost:8082/docker-local/frontend-service:latest